### ISSUE TITLE
Simples Error

### ISSUE THREAD

**Issue by RaFeNiX** [zendesk/zendesk_api_client_php#223]
Hi all,
I've just installed version 2 of the client, copied the main part for a simple test so i have

require 'vendor/autoload.php';
use Zendesk\API\HttpClient as ZendeskAPI;
$subdomain = "domain";
$username  = "mail";
$token     = "token";
$client = new ZendeskAPI($subdomain, $username);
$client->setAuth('basic', ['username' => $username, 'token' => $token]);

$tickets = $client->tickets()->findAll();
print_r($tickets);

and i get the error 

Fatal error: Uncaught exception 'Zendesk\API\Exceptions\ApiResponseException' with message 'Error completing request [url] https://domain.zendesk.com/api/v2/tickets.json [http method] GET [body] ' in C:\xampp\htdocs\protege\middleware\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Http.php:89 Stack trace: #0 C:\xampp\htdocs\protege\middleware\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\HttpClient.php(400): Zendesk\API\Http::send(Object(Zendesk\API\HttpClient), 'tickets.json', Array) #1 C:\xampp\htdocs\protege\middleware\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Traits\Resource\FindAll.php(34): Zendesk\API\HttpClient->get('tickets.json', Array) #2 C:\xampp\htdocs\protege\middleware\createManyTest.php(10): Zendesk\API\Resources\Core\Tickets->findAll() #3 {main} thrown in C:\xampp\htdocs\protege\middleware\vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\Http.php on line 89

what am i doing wrong?

**Comment by RaFeNiX** [comment]
https://github.com/zendesk/zendesk_api_client_php/issues/220  -> answer done, xampp problem with SSL cretificate
