### ISSUE TITLE
Tickets can be updated with Replies?

### ISSUE THREAD

**Issue by imadeelnazar** [zendesk/zendesk_api_client_php#446]
`$client->tickets()->update(15, [
  'priority' => 'urgent',
  'comment'  => [
      'public' => true,
      'body' => 'We have changed your ticket priority to Urgent and will keep you up-to-date asap.'
  ],
]);`

i have added same code but getting this error

`Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://websitedev.zendesk.com/api/v2/tickets/15.json` resulted in a `422 Unprocessable Entity` response: {"error":"RecordInvalid","description":"Record validation errors","details":{"base":[{"description":"Priority: is invali (truncated...) in /home/websites/public_html/my/wp-content/plugins/seoptiks-ticket-system/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /home/websites/public_html/my/wp-content/plugins/seoptiks-ticket-system/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 /home/websites/public_html/my/wp-content/plugins/seoptiks-ticket-system/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /home/websites/public_html/my/wp-content/plugins/seoptiks-ticket-system/vendor/guzzlehttp/promises/src/Promise.php(156): in /home/websites/public_html/my/wp-content/plugins/seoptiks-ticket-system/src/Zendesk/API/Http.php on line 95`

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by ecoologic** [comment]
Closing due to inactivity. Re-open if needed.
