### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Psy\TabCompletion\Matcher\AbstractContextAwareMatcher' not found

### ISSUE THREAD

**Issue by farshidpourlatifi** [zendesk/zendesk_api_client_php#455]
Hi, I am installing zendesk_api_client_php by composer as a dependency for classyllama-module-zendesk-1.0.02 plugin for magento 2.

on magento:di:compile I get this error:

`Fatal error: Uncaught Error: Class 'Psy\TabCompletion\Matcher\AbstractContextAwareMatcher' not found in /home/drmem268/public_html/drmem-live/vendor/zendesk/zendesk_api_client_php/src/Zendesk/Console/Matchers/SubResourceMatcher.php:12
Stack trace:
#0 /home/drmem268/public_html/drmem-live/vendor/composer/ClassLoader.php(444): include()
#1 /home/drmem268/public_html/drmem-live/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/drmem268/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Zendesk\\Console...')
#3 [internal function]: spl_autoload_call('Zendesk\\Console...')
#4 /home/drmem268/public_html/drmem-live/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(133): class_exists('Zendesk\\Console...')
#5 /home/drmem268/public_html/drmem-live/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClasses(Array, '/home/drmem268/...')
#6 /home/drmem268/public_html/drmem-live/setup/src/Magento/S in /home/drmem268/public_html/drmem-live/vendor/zendesk/zendesk_api_client_php/src/Zendesk/Console/Matchers/SubResourceMatcher.php on line 12`

has anyone faced such issue? any guidelines how to fix this?

**Comment by ecoologic** [comment]
Hi,

 thank you for your request,
are you still interested in a solution for this issue?

**Comment by ecoologic** [comment]
Closing due to inactivity. Re-open if needed.
