### ISSUE TITLE
Call to undefined function GuzzleHttp\Psr7\stream_for()

### ISSUE THREAD

**Issue by RobinBoersma** [zendesk/zendesk_api_client_php#470]
`Error: Call to undefined function GuzzleHttp\Psr7\stream_for()
#7 zendesk/zendesk_api_client_php/src/Zendesk/API/Http.php(69): Zendesk\API\Http::send
#6 zendesk/zendesk_api_client_php/src/Zendesk/API/HttpClient.php(494): Zendesk\API\HttpClient::post
#5 zendesk/zendesk_api_client_php/src/Zendesk/API/Resources/Core/Tickets.php(164): Zendesk\API\Resources\Core\Tickets::create`

**Comment by RobinBoersma** [comment]
#471 
#472

**Comment by spencerrlongg** [comment]
this is also fixed via #469 
we'd love to get one of these solutions merged ASAP if at all possible.

**Comment by Bitflinx** [comment]
Quickfix: Goto: \vendor\zendesk\zendesk_api_client_php\src\Zendesk\API\HTTP.php Line 70 and replace

//Corrected cause of error 
$request = $request->withBody(\GuzzleHttp\Psr7\Utils::streamFor(json_encode($options['postFields'])));
			
//Original code
//$request = $request->withBody(\GuzzleHttp\Psr7\stream_for(json_encode($options['postFields'])));

**Comment by kevinirlen** [comment]
I don't know if Zendesk is willing to merge this.. A quick solution, instead of modifying the core files. Create a directory in your project

`GuzzleHttp/psr`

And paste in the code below

```
<?php

namespace GuzzleHttp\Psr7;

/**
 *
 * @param string $resource
 * @param array  $options
 *
 * @return PumpStream|Stream|\Psr\Http\Message\StreamInterface
 */
function stream_for($resource = '', array $options = [])
{
    return Utils::streamFor($resource, $options);
}

```

**Comment by ShadowXVII** [comment]
Merge please @Zendesk 😇

**Comment by BafS** [comment]
@thekindofme, @gkatechis, @gmponos, @nogates sorry to ping you guys but would it be possible to merge one of the fixes? The requirement is not correct and it's easy to mess-up. 

The current workaround is to add a function like @kevinirlen proposes or to require explicitly and old version of `guzzlehttp/psr7` (`composer req "guzzlehttp/psr7:^1"`).

Thanks in advance

**Comment by PierreGranger** [comment]
#471 and #472 would be a perfect response.
This problem is major because any update cause a fault as soon as guzzle is updated to a recent version.

Thanks for your help !

**Comment by paulrwest** [comment]
Any news on a timeframe for a merge? 

Thanks for posting the workarounds guys

**Comment by Pierstoval** [comment]
Do you folks need a cross-compatible version of the fix that would comply with multiple versions of Guzzle, maybe?
At least 3 unmerged PRs: 

* https://github.com/zendesk/zendesk_api_client_php/pull/469
* https://github.com/zendesk/zendesk_api_client_php/pull/471
* https://github.com/zendesk/zendesk_api_client_php/pull/472

A cross-compatible version should be easy, a simple `if (function_exists(...))` should do the trick.

I would've created a PR, but since there's lots of them already, I didn't want to pollute the current state of the project.

However, I'm one of the several people whose production broke because of this, and I had to use a dirty quickfix for that which I don't like at all, so as others, I wish this could be fixed and released soon 😉

**Comment by chrisminett** [comment]
For those following this, it looks like it will have been resolved as #469 has been merged, and these changes are included in release [v2.2.12](https://github.com/zendesk/zendesk_api_client_php/releases/tag/v2.2.12)

**Comment by BafS** [comment]
It seems that packagist is not updated automatically, the last ^v2 is still v2.2.11 (https://packagist.org/packages/zendesk/zendesk_api_client_php). You can use "dev-master" or the specific commit as a workaround.

**Comment by Thewolfs** [comment]
dev-master actually doesn't work directly as it isn't updated on packagist as well. You'll have to add this repository in your composer.json before being able to pull for dev-master or v2.2.11

**Comment by BafS** [comment]
You are right

**Comment by vanessametageek** [comment]
It looks like it is on packagist now.

**Comment by ERuban** [comment]
I have `guzzlehttp/psr7:2.1` dependency in my project. So in my case the last version I'm able to install is `2.2.11` that has this issue 😒

**Comment by gjuric** [comment]
Can you release a new version that allows guzzle psr7 v2 to be installed?

**Comment by ecoologic** [comment]
Closing due to inactivity. Re-open if needed.
